import type { Metadata } from "next"
import { ReactNode } from "react"
import "../globals.css"
import "antd/dist/reset.css"
import { Header } from "@/components/Header/Header"
import { Footer } from "@/components/Footer/Footer"
import AppProviders from "./../providers/AppProviders"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="ru">
      <body className="bg-gray-50 text-gray-900">
        <AppProviders>
          <Header />
          <main className="max-w-screen-xl mx-auto px-6 py-4 min-h-[calc(100vh-60px-225px)]">
            {children}
          </main>
          <Footer />
        </AppProviders>
      </body>
    </html>
  )
}
