/*
  Warnings:

  - The values [KRONSTADTSKY,PETRODVORETSOVY,CENTRALNY] on the enum `District` will be removed. If these variants are still used in the database, this will fail.
  - The values [AKADEMICHESKAYA,BALTISKAYA] on the enum `MetroStation` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "District_new" AS ENUM ('ADMIRALTEYSKY', 'VASILEOSTROVSKY', 'VYBORGSKY', 'KALININSKY', 'KIROVSKY', 'KOLPINSKY', 'KRASNOGVARDEYSKY', 'KRASNOSELSKY', 'KRONSHTADTSKY', 'KURORTNY', 'MOSKOVSKY', 'NEVSKY', 'PETROGRADSKY', 'PETRODVORTSOVY', 'PRIMORSKY', 'PUSHKINSKY', 'FRUNZENSKY', 'TSENTRALNY');
ALTER TABLE "ice_rinks" ALTER COLUMN "district" TYPE "District_new" USING ("district"::text::"District_new");
ALTER TYPE "District" RENAME TO "District_old";
ALTER TYPE "District_new" RENAME TO "District";
DROP TYPE "public"."District_old";
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "MetroStation_new" AS ENUM ('DEVYATKINO', 'GRAZHDANSKIY_PROSPEKT', 'AKADEMICHSKAYA', 'POLITEKHNICHESKAYA', 'PLOSHCHAD_MUZHESTVA', 'LESNAYA', 'VYBORGSKAYA', 'PLOSHCHAD_LENINA', 'CHERNYSHEVSKAYA', 'PLOSHCHAD_VOSSTANIYA', 'VLADIMIRSKAYA', 'PUSHKINSKAYA', 'TEKHNOLOGICHESKIY_INSTITUT_1', 'BALTIYSKAYA', 'NARVSKAYA', 'KIROVSKIY_ZAVOD', 'AVTOVO', 'LENINSKIY_PROSPEKT', 'PROSPEKT_VETERANOV', 'PARNAS', 'PROSPEKT_PROSVESHCHENIYA', 'OZERKI', 'UDELNAYA', 'PIONERSKAYA', 'CHYORNAYA_RECHKA', 'PETROGRADSKAYA', 'GORKOVSKAYA', 'NEVSKIY_PROSPEKT', 'SENNAYA_PLOSHCHAD', 'TEKHNOLOGICHESKIY_INSTITUT_2', 'FRUNZENSKAYA', 'MOSKOVSKIE_VOROTA', 'ELEKTROSILA', 'PARK_POBEDY', 'MOSKOVSKAYA', 'ZVEZDNAYA', 'KUPCHINO', 'BEGOVAYA', 'ZENIT', 'PRIMORSKAYA', 'VASILEOSTROVSKAYA', 'GOSTINY_DVOR', 'MAYAKOVSKAYA', 'PLOSHCHAD_ALEXANDRA_NEVSKOGO_1', 'ELIZAROVSKAYA', 'LOMONOSOVSKAYA', 'PROLETARSKAYA', 'OBUKHOVO', 'RYBATSKOYE', 'GORNY_INSTITUT', 'SPASSKAYA', 'DOSTOEVSKAYA', 'LIGOVSKIY_PROSPEKT', 'PLOSHCHAD_ALEXANDRA_NEVSKOGO_2', 'NOVOCHERKASSKAYA', 'LADOZHSKAYA', 'PROSPEKT_BOLSHEVIKOV', 'ULICA_DYBENKO', 'KOMENDANTSKIY_PROSPEKT', 'STARAYA_DEREVNYA', 'KRESTOVSKIY_OSTROV', 'CHKALOVSKAYA', 'SPORTIVNAYA', 'ADMIRALTEYSKAYA', 'SADOVAYA', 'ZVENIGORODSKAYA', 'OBVODNYY_KANAL', 'VOLKOVSKAYA', 'BUKHARESTSKAYA', 'MEZHDUNARODNAYA', 'PROSPEKT_SLAVY', 'DUNAISKAYA', 'SHUSHARY');
ALTER TABLE "ice_rink_metro" ALTER COLUMN "station" TYPE "MetroStation_new" USING ("station"::text::"MetroStation_new");
ALTER TYPE "MetroStation" RENAME TO "MetroStation_old";
ALTER TYPE "MetroStation_new" RENAME TO "MetroStation";
DROP TYPE "public"."MetroStation_old";
COMMIT;
