export enum FavoritesEnum {
  All = "ALL",
  Favorites = "FAVORITES",
}

export enum RoleEnum {
  Admin = "ADMIN",
  SuperAdmin = "SUPER_ADMIN",
  Sportsman = "SPORTSMAN",
  Parent = "PARENT",
  Coach = "COACH",
}

export enum MetroStationEnum {
  // Линия 1 — Кировско-Выборгская
  DEVYATKINO = "Девяткино",
  GRAZHDANSKIY_PROSPEKT = "Гражданский проспект",
  AKADEMICHSKAYA = "Академическая",
  POLITEKHNICHESKAYA = "Политехническая",
  PLOSHCHAD_MUZHESTVA = "Площадь Мужества",
  LESNAYA = "Лесная",
  VYBORGSKAYA = "Выборгская",
  PLOSHCHAD_LENINA = "Площадь Ленина",
  CHERNYSHEVSKAYA = "Чернышевская",
  PLOSHCHAD_VOSSTANIYA = "Площадь Восстания",
  VLADIMIRSKAYA = "Владимирская",
  PUSHKINSKAYA = "Пушкинская",
  TEKHNOLOGICHESKIY_INSTITUT_1 = "Технологический институт",
  BALTIYSKAYA = "Балтийская",
  NARVSKAYA = "Нарвская",
  KIROVSKIY_ZAVOD = "Кировский завод",
  AVTOVO = "Автово",
  LENINSKIY_PROSPEKT = "Ленинский проспект",
  PROSPEKT_VETERANOV = "Проспект Ветеранов",

  // Линия 2 — Московско-Петроградская
  PARNAS = "Парнас",
  PROSPEKT_PROSVESHCHENIYA = "Проспект Просвещения",
  OZERKI = "Озерки",
  UDELNAYA = "Удельная",
  PIONERSKAYA = "Пионерская",
  CHYORNAYA_RECHKA = "Чёрная речка",
  PETROGRADSKAYA = "Петроградская",
  GORKOVSKAYA = "Горьковская",
  NEVSKIY_PROSPEKT = "Невский проспект",
  SENNAYA_PLOSHCHAD = "Сенная площадь",
  TEKHNOLOGICHESKIY_INSTITUT_2 = "Технологический институт 2",
  FRUNZENSKAYA = "Фрунзенская",
  MOSKOVSKIE_VOROTA = "Московские ворота",
  ELEKTROSILA = "Электросила",
  PARK_POBEDY = "Парк Победы",
  MOSKOVSKAYA = "Московская",
  ZVEZDNAYA = "Звёздная",
  KUPCHINO = "Купчино",

  // Линия 3 — Невско-Василеостровская
  BEGOVAYA = "Беговая",
  ZENIT = "Зенит",
  PRIMORSKAYA = "Приморская",
  VASILEOSTROVSKAYA = "Василеостровская",
  GOSTINY_DVOR = "Гостиный двор",
  MAYAKOVSKAYA = "Маяковская",
  PLOSHCHAD_ALEXANDRA_NEVSKOGO_1 = "Площадь Александра Невского",
  ELIZAROVSKAYA = "Елизаровская",
  LOMONOSOVSKAYA = "Ломоносовская",
  PROLETARSKAYA = "Пролетарская",
  OBUKHOVO = "Обухово",
  RYBATSKOYE = "Рыбацкое",

  // Линия 4 — Правобережная
  GORNY_INSTITUT = "Горный институт",
  SPASSKAYA = "Спасская",
  DOSTOEVSKAYA = "Достоевская",
  LIGOVSKIY_PROSPEKT = "Лиговский проспект",
  PLOSHCHAD_ALEXANDRA_NEVSKOGO_2 = "Площадь Александра Невского 2",
  NOVOCHERKASSKAYA = "Новочеркасская",
  LADOZHSKAYA = "Ладожская",
  PROSPEKT_BOLSHEVIKOV = "Проспект Большевиков",
  ULICA_DYBENKO = "Улица Дыбенко",

  // Линия 5 — Фрунзенско-Приморская
  KOMENDANTSKIY_PROSPEKT = "Комендантский проспект",
  STARAYA_DEREVNYA = "Старая Деревня",
  KRESTOVSKIY_OSTROV = "Крестовский остров",
  CHKALOVSKAYA = "Чкаловская",
  SPORTIVNAYA = "Спортивная",
  ADMIRALTEYSKAYA = "Адмиралтейская",
  SADOVAYA = "Садовая",
  ZVENIGORODSKAYA = "Звенигородская",
  OBVODNYY_KANAL = "Обводный канал",
  VOLKOVSKAYA = "Волковская",
  BUKHARESTSKAYA = "Бухарестская",
  MEZHDUNARODNAYA = "Международная",
  PROSPEKT_SLAVY = "Проспект Славы",
  DUNAISKAYA = "Дунайская",
  SHUSHARY = "Шушары",
}

export enum DistrictEnum {
  ADMIRALTEYSKY = "Адмиралтейский",
  VASILEOSTROVSKY = "Василеостровский",
  VYBORGSKY = "Выборгский",
  KALININSKY = "Калининский",
  KIROVSKY = "Кировский",
  KOLPINSKY = "Колпинский",
  KRASNOGVARDEYSKY = "Красногвардейский",
  KRASNOSELSKY = "Красносельский",
  KRONSHTADTSKY = "Кронштадтский",
  KURORTNY = "Курортный",
  MOSKOVSKY = "Московский",
  NEVSKY = "Невский",
  PETROGRADSKY = "Петроградский",
  PETRODVORTSOVY = "Петродворцовый",
  PRIMORSKY = "Приморский",
  PUSHKINSKY = "Пушкинский",
  FRUNZENSKY = "Фрунзенский",
  TSENTRALNY = "Центральный",
}
