import type { Metadata } from "next"
import { ReactNode } from "react"
import "../../globals.css"
import "antd/dist/reset.css"
import AppProviders from "@/app/providers/AppProviders"

export const metadata: Metadata = {
  title: "Вход",
  description: "Generated by create next app",
}

export default function LoginLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="ru">
      <body className="bg-gray-50 text-gray-900">
        <AppProviders>
          <main className="max-w-screen-xl mx-auto">{children}</main>
        </AppProviders>
      </body>
    </html>
  )
}
