import type { Metadata } from "next"
import { ReactNode } from "react"

export const metadata: Metadata = {
  title: "Вход",
  description: "Generated by create next app",
}

export default function LoginLayout({ children }: Readonly<{ children: ReactNode }>) {
  return <main className="max-w-7xl mx-auto">{children}</main>
}
