import { Layout } from "antd"
import { Content } from "antd/es/layout/layout"
import type { Metadata } from "next"
import { ReactNode } from "react"

import { AppFooter } from "../ui/common/footer/app-footer"
import { Header } from "../ui/common/header/app-header"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <Layout>
      <Header />
      <Content>
        <div className="max-w-7xl mx-4 xl:mx-auto py-4 min-h-[calc(100vh-64px-226px)]">
          {children}
        </div>
      </Content>
      <AppFooter />
    </Layout>
  )
}
