export enum FavoritesEnum {
  All = "ALL",
  Favorites = "FAVORITES",
}

export enum RoleEnum {
  Admin = "ADMIN",
  SuperAdmin = "SUPER_ADMIN",
  Sportsman = "SPORTSMAN",
  Parent = "PARENT",
  Coach = "COACH",
}

export enum RinkTypeEnum {
  All = "ALL",
  Outdoor = "OUTDOOR",
  Indoor = "INDOOR",
}

export enum MetroStationEnum {
  Devyatkino = "DEVYATKINO",
  GrazhdanskiyProspekt = "GRAZHDANSKIY_PROSPEKT",
  Akademichskaya = "AKADEMICHSKAYA",
  Politekhnicheskaya = "POLITEKHNICHESKAYA",
  PloshchadMuzhestva = "PLOSHCHAD_MUZHESTVA",
  Lesnaya = "LESNAYA",
  Vyborgskaya = "VYBORGSKAYA",
  PloshchadLenina = "PLOSHCHAD_LENINA",
  Chernyshevskaya = "CHERNYSHEVSKAYA",
  PloshchadVosstaniya = "PLOSHCHAD_VOSSTANIYA",
  Vladimirskaya = "VLADIMIRSKAYA",
  Pushkinskaya = "PUSHKINSKAYA",
  TekhnologicheskiyInstitut1 = "TEKHNOLOGICHESKIY_INSTITUT_1",
  Baltiyskaya = "BALTIYSKAYA",
  Narvskaya = "NARVSKAYA",
  KirovskiyZavod = "KIROVSKIY_ZAVOD",
  Avtovo = "AVTOVO",
  LeninskiyProspekt = "LENINSKIY_PROSPEKT",
  ProspektVeteranov = "PROSPEKT_VETERANOV",
  Parnas = "PARNAS",
  ProspektProsveshcheniya = "PROSPEKT_PROSVESHCHENIYA",
  Ozerki = "OZERKI",
  Udelnaya = "UDELNAYA",
  Pionerskaya = "PIONERSKAYA",
  ChyornayaRechka = "CHYORNAYA_RECHKA",
  Petrogradskaya = "PETROGRADSKAYA",
  Gorkovskaya = "GORKOVSKAYA",
  NevskiyProspekt = "NEVSKIY_PROSPEKT",
  SennayaPloshchad = "SENNAYA_PLOSHCHAD",
  TekhnologicheskiyInstitut2 = "TEKHNOLOGICHESKIY_INSTITUT_2",
  Frunzenskaya = "FRUNZENSKAYA",
  MoskovskieVorota = "MOSKOVSKIE_VOROTA",
  Elektrosila = "ELEKTROSILA",
  ParkPobedy = "PARK_POBEDY",
  Moskovskaya = "MOSKOVSKAYA",
  Zvezdnaya = "ZVEZDNAYA",
  Kupchino = "KUPCHINO",
  Begovaya = "BEGOVAYA",
  Zenit = "ZENIT",
  Primorskaya = "PRIMORSKAYA",
  Vasileostrovskaya = "VASILEOSTROVSKAYA",
  GostinyDvor = "GOSTINY_DVOR",
  Mayakovskaya = "MAYAKOVSKAYA",
  PloshchadAlexandraNevskogo1 = "PLOSHCHAD_ALEXANDRA_NEVSKOGO_1",
  Elizarovskaya = "ELIZAROVSKAYA",
  Lomonosovskaya = "LOMONOSOVSKAYA",
  Proletarskaya = "PROLETARSKAYA",
  Obukhovo = "OBUKHOVO",
  Rybatskoye = "RYBATSKOYE",
  GornyInstitut = "GORNY_INSTITUT",
  Spasskaya = "SPASSKAYA",
  Dostoevskaya = "DOSTOEVSKAYA",
  LigovskiyProspekt = "LIGOVSKIY_PROSPEKT",
  PloshchadAlexandraNevskogo2 = "PLOSHCHAD_ALEXANDRA_NEVSKOGO_2",
  Novocherkasskaya = "NOVOCHERKASSKAYA",
  Ladozhskaya = "LADOZHSKAYA",
  ProspektBolshevikov = "PROSPEKT_BOLSHEVIKOV",
  UlicaDybenko = "ULICA_DYBENKO",
  KomendantskiyProspekt = "KOMENDANTSKIY_PROSPEKT",
  StarayaDerevnya = "STARAYA_DEREVNYA",
  KrestovskiyOstrov = "KRESTOVSKIY_OSTROV",
  Chkalovskaya = "CHKALOVSKAYA",
  Sportivnaya = "SPORTIVNAYA",
  Admiralteyskaya = "ADMIRALTEYSKAYA",
  Sadovaya = "SADOVAYA",
  Zvenigorodskaya = "ZVENIGORODSKAYA",
  ObvodnyyKanal = "OBVODNYY_KANAL",
  Volkovskaya = "VOLKOVSKAYA",
  Bukharestskaya = "BUKHARESTSKAYA",
  Mezhdunarodnaya = "MEZHDUNARODNAYA",
  ProspektSlavy = "PROSPEKT_SLAVY",
  Dunaiskaya = "DUNAISKAYA",
  Shushary = "SHUSHARY"
}

export enum DistrictEnum {
  Admiralteysky = "ADMIRALTEYSKY",
  Vasileostrovsky = "VASILEOSTROVSKY",
  Vyborgsky = "VYBORGSKY",
  Kalininsky = "KALININSKY",
  Kirovsky = "KIROVSKY",
  Kolpinsky = "KOLPINSKY",
  Krasnogvardeysky = "KRASNOGVARDEYSKY",
  Krasnoselsky = "KRASNOSELSKY",
  Kronshtadtsky = "KRONSHTADTSKY",
  Kurortny = "KURORTNY",
  Moskovsky = "MOSKOVSKY",
  Nevsky = "NEVSKY",
  Petrogradsky = "PETROGRADSKY",
  Petrodvortsovy = "PETRODVORTSOVY",
  Primorsky = "PRIMORSKY",
  Pushkinsky = "PUSHKINSKY",
  Frunzensky = "FRUNZENSKY",
  Tsentralny = "TSENTRALNY",
}
